Feature/login
piyotaro3/RESE pull request #2
Opened 2023-06-07 08:14 UTC by piyotaro3

mainとloginのプルリクエストです。

2023-06-12 00:21 UTC, mona0601 requested changes
レビューしました。
指摘事項を確認してください。

あとAuthenticatedSessionControllerですが、設計書とアクションが異なっているので見直してください。

2023-06-12 00:21 UTC, mona0601 commented on app/Http/Controllers/RegisteredUserController.php
>  class RegisteredUserController extends Controller
Authの下にも同名ファイルがありますが、どっちが正しいのでしょうか？
不要な方は削除してください。

2023-06-12 00:21 UTC, mona0601 commented on app/Http/Controllers/RegisteredUserController.php
> +    public function store(RegisterRequest $request)
登録処理内のeventは何のために必要なのでしょうか？

2023-06-12 00:21 UTC, mona0601 commented on app/Http/Controllers/RegisteredUserController.php
> +    public function store(RegisterRequest $request)
登録処理内でログインしていますが、登録処理は登録処理のみで、登録完了後にログイン画面に遷移してログインすると思っていましたが違うのでしょうか？

2023-06-12 05:18 UTC, piyotaro3 commented on app/Http/Controllers/RegisteredUserController.php
> +    public function store(RegisterRequest $request)
どちらが良いのでしょうか？
私自身が利用するときはログインしておいて欲しいと感じることが多かったのでログインしたままにしていました。
指定がないので運営に確認が必要かもしれません

2023-06-12 05:19 UTC, piyotaro3 commented on app/Http/Controllers/RegisteredUserController.php
> +    public function store(RegisterRequest $request)
larvelの認証機能をそのまま利用していました。
イベントは追加項目のメール認証に利用できると考えていましたが、出来ないでしょうか？

2023-06-12 05:20 UTC, piyotaro3 commented on app/Http/Controllers/RegisteredUserController.php
>  class RegisteredUserController extends Controller
不要なコントローラを削除しました。
必要な物はauth内のコントローラです。

2023-06-12 05:36 UTC, mona0601 commented on app/Http/Controllers/RegisteredUserController.php
> +    public function store(RegisterRequest $request)
どのように利用するの分からないですが、現時点でメール認証は実装されていないので不要コードは削除すべきです。
１行だけですし、メール認証時に必要であれば実装した方がよいですね。

2023-06-12 05:37 UTC, mona0601 commented on app/Http/Controllers/RegisteredUserController.php
> +    public function store(RegisterRequest $request)
会員登録後のサンクスページで「ログインする」ボタンがあるという事は登録時に自動的にログインはしないという仕様に読み取れますね。

2023-06-12 09:21 UTC, piyotaro3 commented on app/Http/Controllers/RegisteredUserController.php
> +    public function store(RegisterRequest $request)
イベントを削除しました。

2023-06-12 09:21 UTC, piyotaro3 commented on app/Http/Controllers/RegisteredUserController.php
> +    public function store(RegisterRequest $request)
会員登録時にログインをしないようにしました。

2023-06-13 07:39 UTC, mona0601 approved these changes
一旦OKです！

2023-06-14 09:09 UTC, merged