Feature/mypage
piyotaro3/RESE pull request #5
Opened 2023-07-06 15:15 UTC by piyotaro3

マイページの作成完了したので、プルリクエストを作成しています。
マイページのデザイン調整の際、ヘッダー部分を少し変更しました。
そのため、店舗一覧の検索機能の位置にずれが発生しています。
ｃｓｓ調整で全体の調整をする際に修正を考えています。

2023-07-12 09:41 UTC, mona0601 requested changes
修正お願いします。

2023-07-12 09:41 UTC, mona0601 commented on app/Http/Controllers/ReserveController.php
> +    public function cansel(Request $request)
cancelです。

2023-07-12 09:41 UTC, mona0601 commented on app/Http/Controllers/ShopController.php
> +
余分なタブが挿入されている？

2023-07-12 09:41 UTC, mona0601 commented on database/migrations/2023_05_25_222205_create_reserves_table.php
> +            $table->softDeletes();//*論理削除用*/
コメントは不要
設計書を変えるか、論理削除にはしないかのいずれか。

2023-07-13 10:09 UTC, piyotaro3 commented on app/Http/Controllers/ReserveController.php
> +    public function cansel(Request $request)
cancelへ修正しました。

2023-07-13 12:53 UTC, piyotaro3 commented on app/Http/Controllers/ShopController.php
> +
不要なタブを削除しました。

2023-07-13 12:54 UTC, piyotaro3 commented on database/migrations/2023_05_25_222205_create_reserves_table.php
> +            $table->softDeletes();//*論理削除用*/
設計書を変更しました。

2023-07-19 09:19 UTC, mona0601 approved these changes
OKです。

2023-07-19 09:21 UTC, merged